// The provisioning side of the backend: parsing what `samba-tool domain
// provision` and `domain passwordsettings show` print, and finding the systemd
// unit a freshly provisioned controller should be started under.
package samba

import (
	"os"
	"regexp"
	"strings"

	"github.com/tui-tools/tui-dc/internal/directory"
)

// ParsePasswordSettings parses `samba-tool domain passwordsettings show` into
// the policy table. Lines are matched against the labels the policy table
// declares, so the parser and the editor cannot point at different settings;
// a line the table does not know is kept as read-only rather than dropped,
// because a future samba-tool may well print one.
func ParsePasswordSettings(out string) directory.PasswordPolicy {
	policy := directory.PasswordPolicy{}
	for _, line := range strings.Split(out, "\n") {
		label, value, ok := splitColon(line)
		if !ok || value == "" {
			continue
		}
		if strings.HasPrefix(label, "Password information for domain") {
			continue
		}
		setting := directory.PolicySetting{Label: label, Value: value}
		if field, known := directory.PolicyFieldByLabel(label); known {
			setting.Name = field.Name
		}
		policy.Settings = append(policy.Settings, setting)
		policy.Read = true
	}
	return policy
}

// ProvisionResult is the part of provision's long output a user must not
// lose: the generated Administrator password, printed exactly once, and the
// note about the Kerberos configuration file it wrote.
type ProvisionResult struct {
	// AdminPassword is what samba-tool printed after "Admin password:". It is
	// generated by samba-tool itself — this tool never put a password
	// anywhere — and this is the only time it can be read.
	AdminPassword string
	// Krb5Conf is the path of the generated Kerberos configuration, from the
	// "A Kerberos configuration suitable for Samba AD has been generated at"
	// line, when it was printed.
	Krb5Conf string
	// Summary is the block of facts provision reports (server role, DNS
	// domain, domain SID …), for the result screen.
	Summary []string
	// Warnings are the WARNING lines provision printed, message only. They are
	// facts about the domain that was just created rather than noise: this is
	// where "More than one IPv4 address found. Using …" appears when the wizard
	// was not told which address to serve, and where "No IPv6 address will be
	// assigned" appears on a host with no IPv6 — both worth reading once,
	// neither visible anywhere afterwards.
	Warnings []string
}

// provisionSummaryLabels are the facts the result screen repeats, in the order
// samba-tool prints them.
var provisionSummaryLabels = []string{"Server Role:", "Hostname:",
	"NetBIOS Domain:", "DNS Domain:", "DOMAIN SID:"}

// ParseProvisionOutput pulls those out of the provision transcript.
//
// Every fact is looked for anywhere in the line, never only at its start:
// samba prints the whole summary through its own logger, so on 4.24 each of
// these lines arrives behind an `INFO <date> pid:<n> <file> #<line>:` prefix,
// and a parser anchored at the start of the line finds none of them — which
// costs the user the one password that exists nowhere else. Older samba prints
// the same facts bare, and both shapes are fixtures here.
func ParseProvisionOutput(out string) ProvisionResult {
	result := ProvisionResult{}
	for _, raw := range strings.Split(out, "\n") {
		line := strings.TrimSpace(raw)
		if value, _, ok := labelled(line, "Admin password:"); ok {
			// Searching the whole line is loose enough that what follows the
			// label has to be checked: a password is exactly one token, so
			// prose that happens to mention one ("Administrator password will
			// be set randomly!") cannot be mistaken for the password itself.
			if fields := strings.Fields(value); len(fields) == 1 {
				result.AdminPassword = fields[0]
			}
			continue
		}
		if message, ok := warningMessage(line); ok {
			result.Warnings = append(result.Warnings, message)
			continue
		}
		if idx := strings.Index(line, "has been generated at"); idx >= 0 &&
			strings.Contains(line, "Kerberos") {
			result.Krb5Conf = strings.TrimSpace(line[idx+len("has been generated at"):])
			continue
		}
		for _, label := range provisionSummaryLabels {
			// The fact is kept from the label on, which drops the log prefix
			// and keeps samba's own column alignment for the screen.
			if _, fact, ok := labelled(line, label); ok {
				result.Summary = append(result.Summary, fact)
			}
		}
	}
	return result
}

// logPrefixRe matches the prefix samba's own logger puts in front of every
// line on 4.24: `WARNING <date> pid:<n> <file> #<line>: `. The message is what
// a reader needs; the file and line number of a Python source file are not.
var logPrefixRe = regexp.MustCompile(`^[A-Z]+ .*#[0-9]+: `)

// warningMessage returns the message of a WARNING line, without the logger's
// prefix. A line that only mentions the word in passing is not one: the level
// is the first word samba prints, so that is where it is looked for.
func warningMessage(line string) (string, bool) {
	if !strings.HasPrefix(line, "WARNING") {
		return "", false
	}
	if prefix := logPrefixRe.FindString(line); prefix != "" {
		message := strings.TrimSpace(line[len(prefix):])
		return message, message != ""
	}
	// Older samba prints the level and the message with nothing between them.
	message := strings.TrimSpace(strings.TrimPrefix(
		strings.TrimPrefix(line, "WARNING"), ":"))
	return message, message != ""
}

// labelled finds a label anywhere in a line and returns what follows it, plus
// the line from the label on.
func labelled(line, label string) (value, fact string, ok bool) {
	idx := strings.Index(line, label)
	if idx < 0 {
		return "", "", false
	}
	return strings.TrimSpace(line[idx+len(label):]), strings.TrimSpace(line[idx:]), true
}

// dcUnitPaths is where the AD DC unit file lives per distribution: Debian and
// Ubuntu ship `samba-ad-dc.service`, Arch and the upstream build ship
// `samba.service` (the same name Fedora uses for smbd, which is why the file
// on disk is checked rather than the name guessed).
var dcUnitPaths = []struct {
	unit  string
	paths []string
}{
	{"samba-ad-dc.service", []string{
		"/usr/lib/systemd/system/samba-ad-dc.service",
		"/lib/systemd/system/samba-ad-dc.service",
	}},
	{"samba.service", []string{
		"/usr/lib/systemd/system/samba.service",
		"/lib/systemd/system/samba.service",
	}},
}

// statFile is os.Stat, replaceable in tests.
var statFile = os.Stat

// DetectDCUnit returns the systemd unit this distribution starts the AD DC
// daemon under, by looking for the unit file itself.
func DetectDCUnit() (string, bool) {
	for _, candidate := range dcUnitPaths {
		for _, path := range candidate.paths {
			if info, err := statFile(path); err == nil && !info.IsDir() {
				return candidate.unit, true
			}
		}
	}
	return "", false
}
