// The provisioning side of the backend: parsing what `samba-tool domain
// provision` and `domain passwordsettings show` print, and finding the systemd
// unit a freshly provisioned controller should be started under.
package samba

import (
	"os"
	"strings"

	"github.com/tui-tools/tui-dc/internal/directory"
)

// ParsePasswordSettings parses `samba-tool domain passwordsettings show` into
// the policy table. Lines are matched against the labels the policy table
// declares, so the parser and the editor cannot point at different settings;
// a line the table does not know is kept as read-only rather than dropped,
// because a future samba-tool may well print one.
func ParsePasswordSettings(out string) directory.PasswordPolicy {
	policy := directory.PasswordPolicy{}
	for _, line := range strings.Split(out, "\n") {
		label, value, ok := splitColon(line)
		if !ok || value == "" {
			continue
		}
		if strings.HasPrefix(label, "Password information for domain") {
			continue
		}
		setting := directory.PolicySetting{Label: label, Value: value}
		if field, known := directory.PolicyFieldByLabel(label); known {
			setting.Name = field.Name
		}
		policy.Settings = append(policy.Settings, setting)
		policy.Read = true
	}
	return policy
}

// ProvisionResult is the part of provision's long output a user must not
// lose: the generated Administrator password, printed exactly once, and the
// note about the Kerberos configuration file it wrote.
type ProvisionResult struct {
	// AdminPassword is what samba-tool printed after "Admin password:". It is
	// generated by samba-tool itself — this tool never put a password
	// anywhere — and this is the only time it can be read.
	AdminPassword string
	// Krb5Conf is the path of the generated Kerberos configuration, from the
	// "A Kerberos configuration suitable for Samba AD has been generated at"
	// line, when it was printed.
	Krb5Conf string
	// Summary is the block of facts provision reports (server role, DNS
	// domain, domain SID …), for the result screen.
	Summary []string
}

// ParseProvisionOutput pulls those out of the provision transcript.
func ParseProvisionOutput(out string) ProvisionResult {
	result := ProvisionResult{}
	for _, raw := range strings.Split(out, "\n") {
		line := strings.TrimSpace(raw)
		if value, ok := strings.CutPrefix(line, "Admin password:"); ok {
			result.AdminPassword = strings.TrimSpace(value)
			continue
		}
		if idx := strings.Index(line, "has been generated at"); idx >= 0 &&
			strings.Contains(line, "Kerberos") {
			result.Krb5Conf = strings.TrimSpace(line[idx+len("has been generated at"):])
			continue
		}
		for _, prefix := range []string{"Server Role:", "Hostname:",
			"NetBIOS Domain:", "DNS Domain:", "DOMAIN SID:"} {
			if strings.HasPrefix(line, prefix) {
				result.Summary = append(result.Summary, line)
			}
		}
	}
	return result
}

// dcUnitPaths is where the AD DC unit file lives per distribution: Debian and
// Ubuntu ship `samba-ad-dc.service`, Arch and the upstream build ship
// `samba.service` (the same name Fedora uses for smbd, which is why the file
// on disk is checked rather than the name guessed).
var dcUnitPaths = []struct {
	unit  string
	paths []string
}{
	{"samba-ad-dc.service", []string{
		"/usr/lib/systemd/system/samba-ad-dc.service",
		"/lib/systemd/system/samba-ad-dc.service",
	}},
	{"samba.service", []string{
		"/usr/lib/systemd/system/samba.service",
		"/lib/systemd/system/samba.service",
	}},
}

// statFile is os.Stat, replaceable in tests.
var statFile = os.Stat

// DetectDCUnit returns the systemd unit this distribution starts the AD DC
// daemon under, by looking for the unit file itself.
func DetectDCUnit() (string, bool) {
	for _, candidate := range dcUnitPaths {
		for _, path := range candidate.paths {
			if info, err := statFile(path); err == nil && !info.IsDir() {
				return candidate.unit, true
			}
		}
	}
	return "", false
}
